# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-node-browsers
      - image: circleci/mysql:5.6-ram     

    working_directory: ~/wp-separate-user-base

    steps:
      - checkout

        # zip: zlib1g-dev
        # gd: libjpeg62-turbo-dev libpng-dev libfreetype6-dev
      - run: sudo apt-get update; sudo apt-get install libicu-dev zlib1g-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev subversion default-mysql-client

      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/

      - run: sudo docker-php-ext-install -j$(nproc) intl bcmath mysqli zip gd
     
      - run:
          name: Setting up php.ini
          command: |
            echo "display_errors = 1" | sudo tee -a /usr/local/etc/php/conf.d/wp-separate-user-base.ini
            echo "display_startup_errors = 1" | sudo tee -a  /usr/local/etc/php/conf.d/wp-separate-user-base.ini
            echo "error_reporting = -1" | sudo tee -a  /usr/local/etc/php/conf.d/wp-separate-user-base.ini

    
      - run: composer install -n --prefer-dist
    

      # Unit Tests
      - run:
          name: Add vendor bin path
          command: |
            echo 'export PATH=~/wp-separate-user-base/vendor/bin:$PATH' >> $BASH_ENV
            source ~/.bashrc
      - run:
          name: Creating common artefact dirs
          command: |
            mkdir -p ~/screenshots
            mkdir -p ~/test-results
            mkdir -p ~/code-coverage

      # Core unit tests
      - run:
          name: Run core unit tests
          command: |
            phpdbg -qrr ~/wp-separate-user-base/vendor/bin/phpunit --coverage-html ~/code-coverage --log-junit ~/results/core.xml


      # Store common artifacts
      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

      - store_artifacts:
          path: ~/code-coverage
     
